services:
  app:
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://benda-te-me.com

  nginx:
    ports: []
    labels:
      - traefik.enable=true

      - traefik.http.routers.benda.rule=Host(`benda-te-me.com`) || Host(`www.benda-te-me.com`)
      - traefik.http.routers.benda.entrypoints=web,websecure
      - traefik.http.routers.benda.tls=true
      - traefik.http.routers.benda.tls.certresolver=mytlschallenge

      - traefik.http.middlewares.benda.headers.STSSeconds=315360000
      - traefik.http.middlewares.benda.headers.browserXSSFilter=true
      - traefik.http.middlewares.benda.headers.contentTypeNosniff=true
      - traefik.http.middlewares.benda.headers.forceSTSHeader=true
      - traefik.http.middlewares.benda.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.benda.headers.STSPreload=true
      - traefik.http.routers.benda.middlewares=benda@docker

      - traefik.http.services.benda.loadbalancer.server.port=80
